name = "one-sub"
main = "src/index.js"
compatibility_date = "2023-09-04"

# 开发环境配置
[dev]
port = 8787
local_protocol = "http"

# 生产环境配置
[env.production]
workers_dev = true

# KV 命名空间
# 正式部署前请在 Cloudflare Dashboard 中创建名为 "ONE_SUB_URLS" 的KV命名空间
# 然后将生成的ID替换下面的 KV_NAMESPACE_ID
#[[kv_namespaces]]
#binding = "KV"
#id = "KV_NAMESPACE_ID"
#preview_id = "KV_NAMESPACE_ID"  # 可选，用于本地开发

[observability]
enabled = true
head_sampling_rate = 1

# 环境变量
#[vars]
## 访问令牌，留空表示不启用验证
#ACCESS_TOKEN = "123"
## 默认配置文件链接，留空表示不使用默认配置
#DEFAULT_CONFIG = ""
## 自定义后端服务地址，留空则使用代码中的默认值
#CUSTOM_BACKEND = ""
## 默认订阅文件名，留空则使用后端默认值
#DEFAULT_FILENAME = "config"
